#!/bin/bash

# ============================================================================
# 快速配置 LLM 提供者
# ============================================================================

set -e

echo "=========================================="
echo "  AI Agent - LLM Provider 配置向导"
echo "=========================================="
echo ""

# 检查 .env.development 是否存在
if [ -f ".env.development" ]; then
    echo "⚠️  .env.development 已存在"
    echo "是否继续配置？(y/n)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "已取消"
        exit 0
    fi
fi

# 选择提供者
echo ""
echo "请选择要配置的 LLM 提供者："
echo "1) OpenAI"
echo "2) Kimi (Moonshot AI)"
echo "3) DeepSeek"
echo "4) GLM (Zhipu AI)"
echo "5) MiniMax"
echo "6) Qwen (Alibaba)"
echo ""
read -p "请输入选项 (1-6): " provider_choice

# 映射提供者类型
case $provider_choice in
    1)
        provider_type="OPENAI"
        default_base_url="https://api.openai.com/v1"
        default_model="gpt-4o-mini"
        ;;
    2)
        provider_type="KIMI"
        default_base_url="https://api.moonshot.cn/v1"
        default_model="kimi-k2.5"
        ;;
    3)
        provider_type="DEEPSEEK"
        default_base_url="https://api.deepseek.com"
        default_model="deepseek-chat"
        ;;
    4)
        provider_type="GLM"
        default_base_url="https://open.bigmodel.cn/api/paas/v4"
        default_model="glm-4-plus"
        ;;
    5)
        provider_type="MINIMAX"
        default_base_url="https://api.minimax.chat/v1"
        default_model="abab6.5s-chat"
        ;;
    6)
        provider_type="QWEN"
        default_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1"
        default_model="qwen-plus"
        ;;
    *)
        echo "❌ 无效选项"
        exit 1
        ;;
esac

# 获取 API Key
echo ""
echo "=========================================="
echo "配置 ${provider_type} 提供者"
echo "=========================================="
echo ""
echo "请输入你的 ${provider_type}_API_KEY:"
read -r api_key

if [ -z "$api_key" ]; then
    echo "❌ API Key 不能为空"
    exit 1
fi

# 获取 Base URL（可选）
echo ""
echo "请输入 Base URL (可选，直接回车使用默认值):"
echo "默认值: ${default_base_url}"
read -r base_url

if [ -z "$base_url" ]; then
    base_url="$default_base_url"
fi

# 获取模型名称（可选）
echo ""
echo "请输入模型名称 (可选，直接回车使用默认值):"
echo "默认值: ${default_model}"
read -r model_name

if [ -z "$model_name" ]; then
    model_name="$default_model"
fi

# 获取 Group ID (仅 MiniMax 需要)
if [ "$provider_type" = "MINIMAX" ]; then
    echo ""
    echo "MiniMax 需要 Group ID"
    echo "请输入你的 MINIMAX_GROUP_ID:"
    read -r group_id

    if [ -z "$group_id" ]; then
        echo "❌ Group ID 不能为空"
        exit 1
    fi
fi

# 获取温度（可选）
echo ""
echo "请输入生成温度 (0-2，可选，直接回车使用默认值):"
echo "默认值: 0.7"
read -r temperature

if [ -z "$temperature" ]; then
    temperature="0.7"
fi

# 创建或更新 .env.development
echo ""
echo "=========================================="
echo "写入配置到 .env.development"
echo "=========================================="

# 创建 .env.development 文件
cat > .env.development <<EOF
# AI Agent Environment Configuration
# Generated by config-provider.sh
# Date: $(date)

# LLM Provider Configuration
AI_MODEL=${model_name}
TEMPERATURE=${temperature}

# ${provider_type} Configuration
${provider_type}_API_KEY=${api_key}
${provider_type}_BASE_URL=${base_url}
EOF

# 添加 MiniMax 特定配置
if [ "$provider_type" = "MINIMAX" ]; then
    echo "MINIMAX_GROUP_ID=${group_id}" >> .env.development
fi

echo ""
echo "✅ 配置完成！"
echo ""
echo "配置摘要:"
echo "  提供者: ${provider_type}"
echo "  模型: ${model_name}"
echo "  API Key: ${api_key:0:8}..."
echo "  Base URL: ${base_url}"
echo "  温度: ${temperature}"

if [ "$provider_type" = "MINIMAX" ]; then
    echo "  Group ID: ${group_id}"
fi

echo ""
echo "下一步:"
echo "  1. 运行 'pnpm dev' 启动开发模式"
echo "  2. 或运行 'pnpm dev:cli-v2-ink' 启动 CLI 界面"
echo ""
